name: common
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  melos: ^3.0.1
  test: ^1.21.0
dependencies:
  grpc: 
    git:
      url: https://github.com/grpc/grpc-dart
