name: server
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  grpc: 
    git:
      url: https://github.com/grpc/grpc-dart
  common:
    path: ../
  orm: ^3.3.0
  json_annotation: ^4.8.0
  fixnum:
  dart_jsonwebtoken: ^2.7.1
  envied: ^0.3.0
  crypto: ^3.0.2
  dbcrypt: ^2.0.0
